export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ADD_BUN = "ADD_BUN";

export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_REQUEST_SUCCESS = "POST_ORDER_REQUEST_SUCCESS";
export const POST_ORDER_REQUEST_ERROR = "POST_ORDER_REQUEST_ERROR";
export const DELETE_ORDER_REQUEST_NUMBER = "DELETE_ORDER_REQUEST_NUMBER";
