export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_REQUEST_SUCCESS: "GET_INGREDIENTS_REQUEST_SUCCESS" =
  "GET_INGREDIENTS_REQUEST_SUCCESS";
export const GET_INGREDIENTS_REQUEST_FAILED: "GET_INGREDIENTS_REQUEST_FAILED" = "GET_INGREDIENTS_REQUEST_FAILED";

export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT: "REMOVE_INGREDIENT" = "REMOVE_INGREDIENT";
export const ADD_BUN: "ADD_BUN" = "ADD_BUN";

export const POST_ORDER_REQUEST: "POST_ORDER_REQUEST" = "POST_ORDER_REQUEST";
export const POST_ORDER_REQUEST_SUCCESS: "POST_ORDER_REQUEST_SUCCESS" = "POST_ORDER_REQUEST_SUCCESS";
export const POST_ORDER_REQUEST_ERROR: "POST_ORDER_REQUEST_ERROR" = "POST_ORDER_REQUEST_ERROR";
export const DELETE_ORDER: "DELETE_ORDER" = "DELETE_ORDER";

export const CHANGE_INGREDIENT_POSITION: "CHANGE_INGREDIENT_POSITION" = "CHANGE_INGREDIENT_POSITION";

export const REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST" = "REGISTER_USER_REQUEST";
export const REGISTER_USER_REQUEST_SUCCESS: "REGISTER_USER_REQUEST_SUCCESS" = "REGISTER_USER_REQUEST_SUCCESS";
export const REGISTER_USER_REQUEST_ERROR: "REGISTER_USER_REQUEST_ERROR" = "REGISTER_USER_REQUEST_ERROR";

export const LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST" = "LOGIN_USER_REQUEST";
export const LOGIN_USER_REQUEST_SUCCESS: "LOGIN_USER_REQUEST_SUCCESS" = "LOGIN_USER_REQUEST_SUCCESS";
export const LOGIN_USER_REQUEST_ERROR: "LOGIN_USER_REQUEST_ERROR" = "LOGIN_USER_REQUEST_ERROR";

export const REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST" = "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_REQUEST_SUCCESS: "REFRESH_TOKEN_REQUEST_SUCCESS" = "REFRESH_TOKEN_REQUEST_SUCCESS";
export const REFRESH_TOKEN_REQUEST_ERROR: "REFRESH_TOKEN_REQUEST_ERROR" = "REFRESH_TOKEN_REQUEST_ERROR";

export const LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST" = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_REQUEST_SUCCESS: "LOGOUT_USER_REQUEST_SUCCESS" = "LOGOUT_USER_REQUEST_SUCCESS";
export const LOGOUT_USER_REQUEST_ERROR: "LOGOUT_USER_REQUEST_ERROR" = "LOGOUT_USER_REQUEST_ERROR";

export const PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST" = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_REQUEST_SUCCESS: "PASSWORD_RESET_REQUEST_SUCCESS" = "PASSWORD_RESET_REQUEST_SUCCESS";
export const PASSWORD_RESET_REQUEST_ERROR: "PASSWORD_RESET_REQUEST_ERROR" = "PASSWORD_RESET_REQUEST_ERROR";

export const PASSWORD_RESET_CODE_REQUEST: "PASSWORD_RESET_CODE_REQUEST" = "PASSWORD_RESET_CODE_REQUEST";
export const PASSWORD_RESET_CODE_REQUEST_SUCCESS: "PASSWORD_RESET_CODE_REQUEST_SUCCESS" =
  "PASSWORD_RESET_CODE_REQUEST_SUCCESS";
export const PASSWORD_RESET_CODE_REQUEST_ERROR: "PASSWORD_RESET_CODE_REQUEST_ERROR" =
  "PASSWORD_RESET_CODE_REQUEST_ERROR";

export const GET_USER_INFO_REQUEST: "GET_USER_INFO_REQUEST" = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_REQUEST_SUCCESS: "GET_USER_INFO_REQUEST_SUCCESS" = "GET_USER_INFO_REQUEST_SUCCESS";
export const GET_USER_INFO_REQUEST_ERROR: "GET_USER_INFO_REQUEST_ERROR" = "GET_USER_INFO_REQUEST_ERROR";

export const PATCH_USER_INFO_REQUEST: "PATCH_USER_INFO_REQUEST" = "PATCH_USER_INFO_REQUEST";
export const PATCH_USER_INFO_REQUEST_SUCCESS: "PATCH_USER_INFO_REQUEST_SUCCESS" =
  "PATCH_USER_INFO_REQUEST_SUCCESS";
export const PATCH_USER_INFO_REQUEST_ERROR: "PATCH_USER_INFO_REQUEST_ERROR" = "PATCH_USER_INFO_REQUEST_ERROR";

export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" = "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" = "WS_CONNECTION_CLOSED";
export const WS_CONNECTION_CLOSE: "WS_CONNECTION_CLOSE" = "WS_CONNECTION_CLOSE";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";
export const WS_SEND_MESSAGE: "WS_SEND_MESSAGE" = "WS_SEND_MESSAGE";

export const WS_CONNECTION_START_AUTH: "WS_CONNECTION_START_AUTH" = "WS_CONNECTION_START_AUTH";
export const WS_CONNECTION_SUCCESS_AUTH: "WS_CONNECTION_SUCCESS_AUTH" = "WS_CONNECTION_SUCCESS_AUTH";
export const WS_CONNECTION_ERROR_AUTH: "WS_CONNECTION_ERROR_AUTH" = "WS_CONNECTION_ERROR_AUTH";
export const WS_CONNECTION_CLOSED_AUTH: "WS_CONNECTION_CLOSED_AUTH" = "WS_CONNECTION_CLOSED_AUTH";
export const WS_CONNECTION_CLOSE_AUTH: "WS_CONNECTION_CLOSE_AUTH" = "WS_CONNECTION_CLOSE_AUTH";
export const WS_GET_MESSAGE_AUTH: "WS_GET_MESSAGE_AUTH" = "WS_GET_MESSAGE_AUTH";
export const WS_SEND_MESSAGE_AUTH: "WS_SEND_MESSAGE_AUTH" = "WS_SEND_MESSAGE_AUTH";
